{
 "title": "Linky - Suivi Conso",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "TIC version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "linky_tic_standard_vtic", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Puissance souscrite",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "linky_tic_standard_pref", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Puissance App. Instantanée",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "linky_tic_standard_sinsts", "legendFormat": "Actuel" }
   ]
  },
  {
   "title": "Consommation accumulée en Wh ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(linky_tic_standard_east_day[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tension eff. instantanée",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "linky_tic_standard_urms1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Courant eff. instantanée",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "linky_tic_standard_irms1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Consommation en Wh",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "delta(linky_tic_standard_east[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consommation en Wh / Jour",
   "type": "barchart",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "last_over_time(linky_tic_standard_east_day[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consommation en kVA",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    { "expr": "linky_tic_standard_sinsts", "legendFormat": "Puissance App." }
   ]
  }
 ]
}